pipeline {
    agent any

    stages {
        stage('yaml-lint') {
            steps {
                script {
                    def lintResult = sh(script: 'yamllint $(find . -name "*.yml" -o -name "*.yaml" )', returnStatus: true)
                    if (lintResult != 0) {
                        error "YAML linting failed"
                    }
                }
            }
        }

        stage('Deploy Containers') {
            steps {
                script {
                    def deployCmd = 'ansible-playbook playbooks/all_containers.yml -i inventory/inventory.yml --tags=test_deployment'
                    def deployResult = sh(script: deployCmd, returnStatus: true)
                    if (deployResult != 0) {
                        error "Failed to deploy containers"
                    }
                }
            }
        }

        stage('Check Containers') {
            steps {
                script {
                    def containers = sh(script: 'docker ps -q', returnStdout: true).trim().split('\n')
                    for (container in containers) {
                        def status = sh(script: "docker inspect --format='{{.State.Status}}' ${container}", returnStdout: true).trim()
                        if (status != 'running') {
                            error "Container ${container} is not running"
                        }
                    }
                }
            }
        }
    }

    // post {
    //     always {
    //         script {
    //             def jenkinsContainerId = sh(script: 'docker ps -q --filter "name=jenkins"', returnStdout: true).trim()
    //             def allContainers = sh(script: 'docker ps -a -q', returnStdout: true).trim().split('\n')
    //             for (containerId in allContainers) {
    //                 if (containerId != jenkinsContainerId) {
    //                     sh "docker stop ${containerId} && docker rm ${containerId}"
    //                 }
    //             }
    //         }
    //     }
    // }
}