---
- name: Run Jenkins container
  docker_container:
    name: jenkins
    image: jenkins/jenkins:lts
    state: started
    ports:
      - "8080:8080"
    restart_policy: always
    networks:
      - name: prometheus-network
    privileged: yes
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

- name: Pause for Jenkins container up
  pause:
    seconds: 10

- name: Update inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get update

- name: Install yamllint inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get install -y yamllint

- name: Install ansible inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get install -y ansible

- name: Install docker inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get install -y docker.io

- name: Install sudo inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get install sudo

- name: Add jenkins user in group docker
  shell: docker exec -it -u root jenkins usermod -aG docker jenkins

- name: Add jenkins user in group sudo
  shell: docker exec -it -u root jenkins usermod -aG sudo jenkins

- name: Install nano inside Jenkins container
  shell: docker exec -it -u root jenkins apt-get install nano

# - name: Changing access rights to docker socket
# yamllint disable-line rule:line-length
#   shell: docker exec -it -u root jenkins chown jenkins:jenkins /var/run/docker.sock && chmod 666 /var/run/docker.sock

# - name: Replace line in file
#   ansible.builtin.lineinfile:
#     path: /etc/sudoers
#     regexp: '^%sudo\s*ALL=(ALL:ALL) ALL$'
#     line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'

- name: Add line in sudoers inside Jenkins container
# yamllint disable-line rule:line-length
  shell: "docker exec -it -u root jenkins sh -c 'echo \"jenkins ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers'"

- name: Retrieve Initial Admin Password
# yamllint disable-line rule:line-length
  shell: docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
  register: initial_admin_password

- debug:
    var: initial_admin_password.stdout
