---
- name: Create Prometheus container
  docker_container:
    name: prometheus_container
    image: ubuntu/prometheus:2.49.1-22.04_stable
    state: started
    ports:
      - "9090:9090"
    networks:
      - name: prometheus-network
    restart_policy: always

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    
- name: Copy Prometheus configuration file using template
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml

- name: Create Node Exporter container
  docker_container:
    name: node_exporter_container
    image: quay.io/prometheus/node-exporter:latest
    state: started
    ports:
      - "9100:9100"
    networks:
      - name: prometheus-network

- name: Create Grafana container
  docker_container:
    name: grafana_container
    image: grafana/grafana
    state: started
    ports:
      - "3000:3000"
    networks:
      - name: prometheus-network