---
- name: Generate index.html from template
  template:
    src: templates/index.html.j2
    dest: /path/to/index.html
    mode: 0644

- name: Run Nginx container
  docker_container:
    name: my_nginx_container
    image: nginx
    state: started
    ports:
     - "80:80"
    volumes:
     - /path/to/index.html:/usr/share/nginx/html/index.html
    networks:
     - name: prometheus-network
